"""
Canonical Multi-Board Curriculum Catalog & Authoritative Exemplar Syllabi.

Authoritative Sources:
- CBSE: Central Board of Secondary Education (CBSE Academic Curriculum 2026-27 / NCERT)
  URL: https://cbseacademic.nic.in/curriculum_2026.html
- CISCE: Council for the Indian School Certificate Examinations (ICSE / ISC Syllabuses 2026-27)
  URL: https://www.cisce.org/regulations-and-syllabuses-isc/
- State Board: National Core Curriculum Baseline (Provisional / In Preparation)
  URL: https://ncert.nic.in
- Other: General Flexible Framework (Provisional / In Preparation)
  URL: https://smartlearn.ai

Curriculum Status Tiers:
- 'catalogued': Catalog entry registered in canonical database; structure curation in progress.
- 'curriculum_verified': Chapter and topic hierarchy verified against official board syllabus document.
- 'content_available': Verified curriculum structure with textbook notes, learning resources, and practice questions.
- 'in_preparation': Subject record established; authoritative syllabus actively under compilation.
"""

from typing import Any, Dict, List, Optional

# ─────────────────────────────────────────────────────────────────────────────
# 1. CANONICAL SUBJECT CATALOG
# Every advertised board, grade, and stream mapped to a stable, unique subject record.
# ─────────────────────────────────────────────────────────────────────────────

CANONICAL_SUBJECTS_CATALOG: List[Dict[str, Any]] = [
    # ═════════════════════════════════════════════════════════════════════════
    # CBSE: Classes 6, 7, 8 (Middle School)
    # ═════════════════════════════════════════════════════════════════════════
    *(
        [
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-eng",
                "name": "English Language & Literature",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"CBSE {g} English Language and Literature curriculum based on NCERT syllabus.",
                "display_order": 1,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hin",
                "name": "Hindi",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"CBSE {g} Hindi curriculum based on NCERT syllabus.",
                "display_order": 2,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-math",
                "name": "Mathematics",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CBSE {g} Mathematics curriculum based on NCERT syllabus.",
                "display_order": 3,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci",
                "name": "Science",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CBSE {g} General Science curriculum based on NCERT syllabus.",
                "display_order": 4,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-soc",
                "name": "Social Science",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CBSE {g} Social Science (History, Geography, Civics) based on NCERT.",
                "display_order": 5,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-san",
                "name": "Sanskrit / Third Language",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"CBSE {g} Third Language curriculum.",
                "display_order": 6,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-cs",
                "name": "Computer Science",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "skill",
                "description": f"CBSE {g} Foundational Computer Literacy & Coding.",
                "display_order": 7,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
        ]
        for g in ["Class 6", "Class 7", "Class 8"]
    ),
    # ═════════════════════════════════════════════════════════════════════════
    # CBSE: Classes 9 & 10 (Secondary)
    # ═════════════════════════════════════════════════════════════════════════
    *(
        [
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-math-std",
                "name": "Mathematics Standard",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CBSE {g} Mathematics (Standard) - Code 041, aligned with NCERT curriculum.",
                "display_order": 1,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "curriculum_verified" if g == "Class 10" else "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-math-basic",
                "name": "Mathematics Basic",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CBSE {g} Mathematics (Basic) - Code 241, aligned with NCERT curriculum.",
                "display_order": 2,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci",
                "name": "Science",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CBSE {g} Science - Code 086, covering Physics, Chemistry, and Biology.",
                "display_order": 3,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "curriculum_verified" if g == "Class 10" else "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-soc",
                "name": "Social Science",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CBSE {g} Social Science - Code 087 (History, Geography, Political Science, Economics).",
                "display_order": 4,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-eng",
                "name": "English Language & Literature",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"CBSE {g} English Language & Literature - Code 184.",
                "display_order": 5,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hin-a",
                "name": "Hindi Course-A",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"CBSE {g} Hindi Course-A - Code 002.",
                "display_order": 6,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hin-b",
                "name": "Hindi Course-B",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"CBSE {g} Hindi Course-B - Code 085.",
                "display_order": 7,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-it",
                "name": "Information Technology",
                "board": "CBSE",
                "grade": g,
                "academic_stream": None,
                "category": "skill",
                "description": f"CBSE {g} Information Technology - Code 402.",
                "display_order": 8,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
        ]
        for g in ["Class 9", "Class 10"]
    ),
    # ═════════════════════════════════════════════════════════════════════════
    # CBSE: Classes 11 & 12 (Senior Secondary - Streams)
    # ═════════════════════════════════════════════════════════════════════════
    *(
        [
            # Science Stream
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci-eng",
                "name": "English Core",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Science",
                "category": "language",
                "description": f"CBSE {g} English Core - Code 301.",
                "display_order": 1,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci-phy",
                "name": "Physics",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CBSE {g} Physics - Code 042, aligned with NCERT textbook.",
                "display_order": 2,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "curriculum_verified" if g == "Class 12" else "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci-chem",
                "name": "Chemistry",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CBSE {g} Chemistry - Code 043.",
                "display_order": 3,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci-math",
                "name": "Mathematics",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CBSE {g} Mathematics - Code 041.",
                "display_order": 4,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci-appmath",
                "name": "Applied Mathematics",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CBSE {g} Applied Mathematics - Code 241.",
                "display_order": 5,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci-bio",
                "name": "Biology",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CBSE {g} Biology - Code 044.",
                "display_order": 6,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci-cs",
                "name": "Computer Science",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CBSE {g} Computer Science - Code 083.",
                "display_order": 7,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci-ip",
                "name": "Informatics Practices",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CBSE {g} Informatics Practices - Code 065.",
                "display_order": 8,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-sci-pe",
                "name": "Physical Education",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Science",
                "category": "skill",
                "description": f"CBSE {g} Physical Education - Code 048.",
                "display_order": 9,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Commerce Stream
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-comm-eng",
                "name": "English Core",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "language",
                "description": f"CBSE {g} English Core - Code 301.",
                "display_order": 1,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-comm-acc",
                "name": "Accountancy",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CBSE {g} Accountancy - Code 055.",
                "display_order": 2,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-comm-bst",
                "name": "Business Studies",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CBSE {g} Business Studies - Code 054.",
                "display_order": 3,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-comm-eco",
                "name": "Economics",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CBSE {g} Economics - Code 030.",
                "display_order": 4,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-comm-math",
                "name": "Mathematics",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CBSE {g} Mathematics - Code 041.",
                "display_order": 5,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-comm-appmath",
                "name": "Applied Mathematics",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CBSE {g} Applied Mathematics - Code 241.",
                "display_order": 6,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-comm-ip",
                "name": "Informatics Practices",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CBSE {g} Informatics Practices - Code 065.",
                "display_order": 7,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-comm-pe",
                "name": "Physical Education",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "skill",
                "description": f"CBSE {g} Physical Education - Code 048.",
                "display_order": 8,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Humanities / Arts Stream
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hum-eng",
                "name": "English Core",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "language",
                "description": f"CBSE {g} English Core - Code 301.",
                "display_order": 1,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hum-hist",
                "name": "History",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CBSE {g} History - Code 027 (Themes in World/Indian History).",
                "display_order": 2,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hum-pol",
                "name": "Political Science",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CBSE {g} Political Science - Code 028.",
                "display_order": 3,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hum-geo",
                "name": "Geography",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CBSE {g} Geography - Code 029.",
                "display_order": 4,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hum-eco",
                "name": "Economics",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CBSE {g} Economics - Code 030.",
                "display_order": 5,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hum-psych",
                "name": "Psychology",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CBSE {g} Psychology - Code 037.",
                "display_order": 6,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hum-soc",
                "name": "Sociology",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CBSE {g} Sociology - Code 039.",
                "display_order": 7,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-hum-hin",
                "name": "Hindi Core",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "language",
                "description": f"CBSE {g} Hindi Core - Code 302.",
                "display_order": 8,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Other Stream
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-oth-eng",
                "name": "English Core",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Other",
                "category": "language",
                "description": f"CBSE {g} English Core - Code 301.",
                "display_order": 1,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-oth-math",
                "name": "Mathematics",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Other",
                "category": "elective",
                "description": f"CBSE {g} Mathematics - Code 041.",
                "display_order": 2,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"cbse-{g.lower().replace(' ', '-')}-oth-cs",
                "name": "Computer Science",
                "board": "CBSE",
                "grade": g,
                "academic_stream": "Other",
                "category": "elective",
                "description": f"CBSE {g} Computer Science - Code 083.",
                "display_order": 3,
                "source_authority": "CBSE / NCERT",
                "source_url": "https://cbseacademic.nic.in/curriculum_2026.html",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
        ]
        for g in ["Class 11", "Class 12"]
    ),
    # ═════════════════════════════════════════════════════════════════════════
    # ICSE: Classes 6, 7, 8, 9, 10
    # ═════════════════════════════════════════════════════════════════════════
    *(
        [
            {
                "code": f"icse-{g.lower().replace(' ', '-')}-eng",
                "name": "English",
                "board": "ICSE",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"CISCE ICSE {g} English Language & Literature.",
                "display_order": 1,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-icse/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"icse-{g.lower().replace(' ', '-')}-lang",
                "name": "Second Language",
                "board": "ICSE",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"CISCE ICSE {g} Second Language.",
                "display_order": 2,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-icse/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"icse-{g.lower().replace(' ', '-')}-hcg",
                "name": "History, Civics and Geography",
                "board": "ICSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CISCE ICSE {g} History, Civics and Geography (HCG Paper 1 & 2).",
                "display_order": 3,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-icse/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "curriculum_verified" if g == "Class 10" else "in_preparation",
            },
            {
                "code": f"icse-{g.lower().replace(' ', '-')}-math",
                "name": "Mathematics",
                "board": "ICSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CISCE ICSE {g} Mathematics.",
                "display_order": 4,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-icse/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"icse-{g.lower().replace(' ', '-')}-sci",
                "name": "Science (Physics, Chemistry, Biology)",
                "board": "ICSE",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"CISCE ICSE {g} Science covering Physics, Chemistry, and Biology.",
                "display_order": 5,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-icse/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"icse-{g.lower().replace(' ', '-')}-eco",
                "name": "Economics",
                "board": "ICSE",
                "grade": g,
                "academic_stream": None,
                "category": "elective",
                "description": f"CISCE ICSE {g} Economics elective.",
                "display_order": 6,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-icse/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"icse-{g.lower().replace(' ', '-')}-comp-app",
                "name": "Computer Applications",
                "board": "ICSE",
                "grade": g,
                "academic_stream": None,
                "category": "skill",
                "description": f"CISCE ICSE {g} Computer Applications.",
                "display_order": 7,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-icse/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"icse-{g.lower().replace(' ', '-')}-comm-studies",
                "name": "Commercial Studies",
                "board": "ICSE",
                "grade": g,
                "academic_stream": None,
                "category": "elective",
                "description": f"CISCE ICSE {g} Commercial Studies.",
                "display_order": 8,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-icse/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
        ]
        for g in ["Class 6", "Class 7", "Class 8", "Class 9", "Class 10"]
    ),
    # ═════════════════════════════════════════════════════════════════════════
    # ISC: Classes 11 & 12 (Senior Secondary - Streams)
    # NOTE: ISC Class 11 Humanities / Arts History must use stable code "isc-11-hist"
    # to preserve existing database record (ID=43) and student progress.
    # ═════════════════════════════════════════════════════════════════════════
    *(
        [
            # Science Stream
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-sci-eng",
                "name": "English",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Science",
                "category": "language",
                "description": f"CISCE ISC {g} English Compulsory.",
                "display_order": 1,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-sci-phy",
                "name": "Physics",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CISCE ISC {g} Physics.",
                "display_order": 2,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-sci-chem",
                "name": "Chemistry",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CISCE ISC {g} Chemistry.",
                "display_order": 3,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-sci-math",
                "name": "Mathematics",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CISCE ISC {g} Mathematics.",
                "display_order": 4,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-sci-bio",
                "name": "Biology",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CISCE ISC {g} Biology.",
                "display_order": 5,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-sci-cs",
                "name": "Computer Science",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CISCE ISC {g} Computer Science.",
                "display_order": 6,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-sci-biotech",
                "name": "Biotechnology",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"CISCE ISC {g} Biotechnology.",
                "display_order": 7,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Commerce Stream
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-comm-eng",
                "name": "English",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "language",
                "description": f"CISCE ISC {g} English Compulsory.",
                "display_order": 1,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-comm-acc",
                "name": "Accounts",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CISCE ISC {g} Accounts.",
                "display_order": 2,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-comm-comm",
                "name": "Commerce",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CISCE ISC {g} Commerce.",
                "display_order": 3,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-comm-eco",
                "name": "Economics",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CISCE ISC {g} Economics.",
                "display_order": 4,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-comm-bst",
                "name": "Business Studies",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CISCE ISC {g} Business Studies.",
                "display_order": 5,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-comm-math",
                "name": "Mathematics",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"CISCE ISC {g} Mathematics.",
                "display_order": 6,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Humanities / Arts Stream
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-hum-eng",
                "name": "English",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "language",
                "description": f"CISCE ISC {g} English Compulsory.",
                "display_order": 1,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                # Stable code for Class 11 History preserves ID 43
                "code": "isc-11-hist" if g == "Class 11" else "isc-12-hum-hist",
                "name": "History",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": (
                    "Official CISCE ISC Class XI History curriculum covering Section A (Indian History) "
                    "and Section B (World History) for Examination Year 2027."
                    if g == "Class 11"
                    else f"CISCE ISC {g} History."
                ),
                "display_order": 2,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Examination Year 2027" if g == "Class 11" else "Academic Year 2026-27",
                "curriculum_status": "content_available" if g == "Class 11" else "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-hum-pol",
                "name": "Political Science",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CISCE ISC {g} Political Science.",
                "display_order": 3,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-hum-geo",
                "name": "Geography",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CISCE ISC {g} Geography.",
                "display_order": 4,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-hum-soc",
                "name": "Sociology",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CISCE ISC {g} Sociology.",
                "display_order": 5,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-hum-psych",
                "name": "Psychology",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CISCE ISC {g} Psychology.",
                "display_order": 6,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-hum-eco",
                "name": "Economics",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"CISCE ISC {g} Economics.",
                "display_order": 7,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Other Stream
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-oth-eng",
                "name": "English",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Other",
                "category": "language",
                "description": f"CISCE ISC {g} English Compulsory.",
                "display_order": 1,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-oth-math",
                "name": "Mathematics",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Other",
                "category": "elective",
                "description": f"CISCE ISC {g} Mathematics.",
                "display_order": 2,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"isc-{g.lower().replace(' ', '-')}-oth-cs",
                "name": "Computer Science",
                "board": "ISC",
                "grade": g,
                "academic_stream": "Other",
                "category": "elective",
                "description": f"CISCE ISC {g} Computer Science.",
                "display_order": 3,
                "source_authority": "CISCE",
                "source_url": "https://www.cisce.org/regulations-and-syllabuses-isc/",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
        ]
        for g in ["Class 11", "Class 12"]
    ),
    # ═════════════════════════════════════════════════════════════════════════
    # State Board: Baseline Classes 6 to 12
    # ═════════════════════════════════════════════════════════════════════════
    *(
        [
            {
                "code": f"state-{g.lower().replace(' ', '-')}-first-lang",
                "name": "First Language (Regional Language / Mother Tongue)",
                "board": "State Board",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"State Board {g} First Language (Provisional Baseline).",
                "display_order": 1,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-second-lang",
                "name": "Second Language (English / Hindi)",
                "board": "State Board",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"State Board {g} Second Language (Provisional Baseline).",
                "display_order": 2,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-math",
                "name": "Mathematics",
                "board": "State Board",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"State Board {g} Mathematics (Provisional Baseline).",
                "display_order": 3,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-sci",
                "name": "Science & Technology",
                "board": "State Board",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"State Board {g} Science & Technology (Provisional Baseline).",
                "display_order": 4,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-soc",
                "name": "Social Sciences",
                "board": "State Board",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"State Board {g} Social Sciences (Provisional Baseline).",
                "display_order": 5,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
        ]
        for g in ["Class 6", "Class 7", "Class 8", "Class 9", "Class 10"]
    ),
    *(
        [
            # Senior Science
            {
                "code": f"state-{g.lower().replace(' ', '-')}-sci-eng",
                "name": "English",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Science",
                "category": "language",
                "description": f"State Board {g} English Compulsory.",
                "display_order": 1,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-sci-phy",
                "name": "Physics",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"State Board {g} Physics.",
                "display_order": 2,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-sci-chem",
                "name": "Chemistry",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"State Board {g} Chemistry.",
                "display_order": 3,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-sci-math",
                "name": "Mathematics",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"State Board {g} Mathematics.",
                "display_order": 4,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-sci-bio",
                "name": "Biology",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"State Board {g} Biology.",
                "display_order": 5,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Senior Commerce
            {
                "code": f"state-{g.lower().replace(' ', '-')}-comm-eng",
                "name": "English",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "language",
                "description": f"State Board {g} English Compulsory.",
                "display_order": 1,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-comm-acc",
                "name": "Accountancy",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"State Board {g} Accountancy.",
                "display_order": 2,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-comm-comm",
                "name": "Commerce / Organisation of Commerce",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"State Board {g} Commerce.",
                "display_order": 3,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-comm-eco",
                "name": "Economics",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"State Board {g} Economics.",
                "display_order": 4,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Senior Humanities
            {
                "code": f"state-{g.lower().replace(' ', '-')}-hum-eng",
                "name": "English",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "language",
                "description": f"State Board {g} English Compulsory.",
                "display_order": 1,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-hum-hist",
                "name": "History",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"State Board {g} History.",
                "display_order": 2,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-hum-pol",
                "name": "Political Science",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"State Board {g} Political Science.",
                "display_order": 3,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"state-{g.lower().replace(' ', '-')}-hum-geo",
                "name": "Geography",
                "board": "State Board",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"State Board {g} Geography.",
                "display_order": 4,
                "source_authority": "State Education Boards Baseline",
                "source_url": "https://ncert.nic.in",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
        ]
        for g in ["Class 11", "Class 12"]
    ),
    # ═════════════════════════════════════════════════════════════════════════
    # Other / General Flexible Framework
    # ═════════════════════════════════════════════════════════════════════════
    *(
        [
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-eng",
                "name": "English Language & Literature",
                "board": "Other",
                "grade": g,
                "academic_stream": None,
                "category": "language",
                "description": f"General Curriculum {g} English Language & Literature.",
                "display_order": 1,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-math",
                "name": "Mathematics",
                "board": "Other",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"General Curriculum {g} Mathematics.",
                "display_order": 2,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-sci",
                "name": "General Science / Integrated Science",
                "board": "Other",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"General Curriculum {g} General Science.",
                "display_order": 3,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-soc",
                "name": "Social Studies / Humanities",
                "board": "Other",
                "grade": g,
                "academic_stream": None,
                "category": "core",
                "description": f"General Curriculum {g} Social Studies.",
                "display_order": 4,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
        ]
        for g in ["Class 6", "Class 7", "Class 8", "Class 9", "Class 10"]
    ),
    *(
        [
            # Senior Science
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-sci-phy",
                "name": "Physics",
                "board": "Other",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"General Curriculum {g} Physics.",
                "display_order": 1,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-sci-chem",
                "name": "Chemistry",
                "board": "Other",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"General Curriculum {g} Chemistry.",
                "display_order": 2,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-sci-math",
                "name": "Mathematics",
                "board": "Other",
                "grade": g,
                "academic_stream": "Science",
                "category": "elective",
                "description": f"General Curriculum {g} Mathematics.",
                "display_order": 3,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Senior Commerce
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-comm-acc",
                "name": "Accounting",
                "board": "Other",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"General Curriculum {g} Accounting.",
                "display_order": 1,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-comm-eco",
                "name": "Economics",
                "board": "Other",
                "grade": g,
                "academic_stream": "Commerce",
                "category": "elective",
                "description": f"General Curriculum {g} Economics.",
                "display_order": 2,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            # Senior Humanities
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-hum-hist",
                "name": "World History",
                "board": "Other",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"General Curriculum {g} World History.",
                "display_order": 1,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
            {
                "code": f"oth-{g.lower().replace(' ', '-')}-hum-pol",
                "name": "Global Politics / Political Science",
                "board": "Other",
                "grade": g,
                "academic_stream": "Humanities / Arts",
                "category": "elective",
                "description": f"General Curriculum {g} Global Politics.",
                "display_order": 2,
                "source_authority": "General Educational Framework",
                "source_url": "https://smartlearn.ai",
                "syllabus_version": "Academic Year 2026-27",
                "curriculum_status": "in_preparation",
            },
        ]
        for g in ["Class 11", "Class 12"]
    ),
]


def _flatten_catalog(items: List[Any]) -> List[Dict[str, Any]]:
    flat: List[Dict[str, Any]] = []
    for item in items:
        if isinstance(item, list):
            flat.extend(_flatten_catalog(item))
        elif isinstance(item, dict):
            flat.append(item)
    return flat


CANONICAL_SUBJECTS_CATALOG = _flatten_catalog(CANONICAL_SUBJECTS_CATALOG)


# ─────────────────────────────────────────────────────────────────────────────
# 2. AUTHORITATIVE EXEMPLAR SYLLABUS STRUCTURES
# Official chapter & topic structures sourced from verified curriculum documents.
# ─────────────────────────────────────────────────────────────────────────────

# Exemplar 1: CBSE Class 10 Science (Code 086) - 13 Official NCERT Chapters
CBSE_10_SCIENCE_SYLLABUS = {
    "code": "cbse-class-10-sci",
    "name": "Science",
    "board": "CBSE",
    "grade": "Class 10",
    "academic_stream": None,
    "chapters": [
        {
            "chapter_number": 1,
            "title": "Chemical Reactions and Equations",
            "description": "Chemical equations, balanced chemical equations, types of chemical reactions, effects of oxidation reactions in everyday life.",
            "topics": [
                {"topic_number": 1, "title": "Chemical Equations and Balancing", "estimated_minutes": 25, "description": "Writing chemical equations, skeletal equations, step-by-step balancing method."},
                {"topic_number": 2, "title": "Types of Chemical Reactions", "estimated_minutes": 30, "description": "Combination, decomposition, displacement, double displacement, and precipitation reactions."},
                {"topic_number": 3, "title": "Oxidation, Reduction, Corrosion and Rancidity", "estimated_minutes": 20, "description": "Oxidation and reduction processes, redox reactions, causes and prevention of corrosion and rancidity."},
            ],
        },
        {
            "chapter_number": 2,
            "title": "Acids, Bases and Salts",
            "description": "Chemical properties of acids and bases, pH scale and everyday importance, salts family and preparation.",
            "topics": [
                {"topic_number": 1, "title": "Properties of Acids and Bases", "estimated_minutes": 25, "description": "Indicators, reactions with metals, metal carbonates, and hydrogen carbonates."},
                {"topic_number": 2, "title": "The pH Scale and Importance in Daily Life", "estimated_minutes": 25, "description": "Concept of pH, universal indicator, pH of digestive system, tooth decay, soil."},
                {"topic_number": 3, "title": "Common Salts and Their Industrial Applications", "estimated_minutes": 30, "description": "Sodium hydroxide, bleaching powder, baking soda, washing soda, plaster of Paris."},
            ],
        },
        {
            "chapter_number": 3,
            "title": "Metals and Non-metals",
            "description": "Physical and chemical properties of metals and non-metals, reactivity series, ionic compounds, extraction of metals.",
            "topics": [
                {"topic_number": 1, "title": "Physical and Chemical Properties of Metals and Non-metals", "estimated_minutes": 25, "description": "Reactivity with air, water, and acids; metal reactivity series."},
                {"topic_number": 2, "title": "Formation and Properties of Ionic Compounds", "estimated_minutes": 25, "description": "Electron dot structures, ionic bonding, crystal lattice, physical properties."},
                {"topic_number": 3, "title": "Basic Metallurgical Processes and Corrosion Prevention", "estimated_minutes": 25, "description": "Occurrence of metals, roasting, calcination, reduction, refining, alloying."},
            ],
        },
        {
            "chapter_number": 4,
            "title": "Carbon and its Compounds",
            "description": "Covalent bonding in carbon compounds, homologous series, functional groups, chemical properties, ethanol and ethanoic acid, soaps.",
            "topics": [
                {"topic_number": 1, "title": "Covalent Bonding and Versatile Nature of Carbon", "estimated_minutes": 25, "description": "Tetravalency, catenation, saturated and unsaturated hydrocarbons, structural isomerism."},
                {"topic_number": 2, "title": "Functional Groups, Homologous Series and Nomenclature", "estimated_minutes": 30, "description": "Halogens, alcohols, aldehydes, ketones, carboxylic acids, systematic naming rules."},
                {"topic_number": 3, "title": "Chemical Properties of Carbon Compounds, Ethanol, Soaps", "estimated_minutes": 30, "description": "Combustion, oxidation, addition, substitution, properties of ethanol and ethanoic acid, cleansing action of soap."},
            ],
        },
        {
            "chapter_number": 5,
            "title": "Life Processes",
            "description": "Fundamental metabolic processes maintaining life: nutrition, respiration, transportation, and excretion.",
            "topics": [
                {"topic_number": 1, "title": "Autotrophic and Heterotrophic Nutrition", "estimated_minutes": 30, "description": "Photosynthesis mechanisms, human alimentary canal, digestive enzymes."},
                {"topic_number": 2, "title": "Respiration in Plants and Animals", "estimated_minutes": 25, "description": "Aerobic vs anaerobic pathway, human respiratory system, gas exchange in alveoli."},
                {"topic_number": 3, "title": "Circulation and Transportation in Humans and Plants", "estimated_minutes": 30, "description": "Structure and function of human heart, double circulation, xylem and phloem transport."},
                {"topic_number": 4, "title": "Excretion in Human Beings and Plants", "estimated_minutes": 20, "description": "Structure of nephron, urine formation mechanisms, dialyzer, plant excretion mechanisms."},
            ],
        },
        {
            "chapter_number": 6,
            "title": "Control and Coordination",
            "description": "Nervous and hormonal systems in animals, reflex arcs, plant tropisms and phytohormones.",
            "topics": [
                {"topic_number": 1, "title": "Nervous System, Reflex Arc, and Human Brain", "estimated_minutes": 30, "description": "Neuron structure, synapse, reflex action, cerebrum, cerebellum, medulla."},
                {"topic_number": 2, "title": "Plant Hormones and Tropic Movements", "estimated_minutes": 20, "description": "Auxins, gibberellins, cytokinins, abscisic acid; phototropism, geotropism, hydrotropism."},
                {"topic_number": 3, "title": "Endocrine System and Hormones in Animals", "estimated_minutes": 25, "description": "Pituitary, thyroid, adrenal, pancreas glands; feedback mechanisms."},
            ],
        },
        {
            "chapter_number": 7,
            "title": "How do Organisms Reproduce?",
            "description": "Asexual and sexual reproduction, flower reproduction, human reproductive system, reproductive health.",
            "topics": [
                {"topic_number": 1, "title": "Modes of Asexual Reproduction", "estimated_minutes": 20, "description": "Fission, fragmentation, regeneration, budding, vegetative propagation, spore formation."},
                {"topic_number": 2, "title": "Sexual Reproduction in Flowering Plants", "estimated_minutes": 25, "description": "Structure of flower, pollination, fertilization, seed germination."},
                {"topic_number": 3, "title": "Human Reproductive System and Reproductive Health", "estimated_minutes": 30, "description": "Male and female reproductive organs, menstrual cycle, contraception methods, STDs."},
            ],
        },
        {
            "chapter_number": 8,
            "title": "Heredity and Evolution",
            "description": "Heredity mechanisms, Mendel's inheritance laws, monohybrid and dihybrid crosses, sex determination.",
            "topics": [
                {"topic_number": 1, "title": "Mendel's Laws of Inheritance", "estimated_minutes": 30, "description": "Dominant and recessive traits, law of segregation, independent assortment."},
                {"topic_number": 2, "title": "Sex Determination in Humans", "estimated_minutes": 20, "description": "Role of XX and XY chromosomes in sex determination of human offspring."},
            ],
        },
        {
            "chapter_number": 9,
            "title": "Light – Reflection and Refraction",
            "description": "Reflection by spherical mirrors, refraction through lenses, lens and mirror formulas, magnification and power.",
            "topics": [
                {"topic_number": 1, "title": "Reflection of Light by Spherical Mirrors", "estimated_minutes": 30, "description": "Concave and convex mirrors, ray diagrams, sign convention, mirror formula."},
                {"topic_number": 2, "title": "Refraction of Light and Snell's Law", "estimated_minutes": 25, "description": "Refractive index, optical density, refraction through rectangular glass slab."},
                {"topic_number": 3, "title": "Lenses, Lens Formula, and Optical Power", "estimated_minutes": 30, "description": "Convex and concave lenses, ray diagrams, lens formula, magnification, dioptre."},
            ],
        },
        {
            "chapter_number": 10,
            "title": "The Human Eye and the Colourful World",
            "description": "Anatomy of human eye, vision defects, dispersion through prism, atmospheric refraction, scattering.",
            "topics": [
                {"topic_number": 1, "title": "Human Eye Anatomy and Vision Defects", "estimated_minutes": 25, "description": "Accommodation, myopia, hypermetropia, presbyopia and their corrective lenses."},
                {"topic_number": 2, "title": "Refraction through Prism and Dispersion", "estimated_minutes": 25, "description": "Angle of deviation, dispersion into spectrum, rainbow formation mechanism."},
                {"topic_number": 3, "title": "Atmospheric Refraction and Scattering of Light", "estimated_minutes": 20, "description": "Twinkling of stars, advance sunrise and delayed sunset, Tyndall effect, blue sky."},
            ],
        },
        {
            "chapter_number": 11,
            "title": "Electricity",
            "description": "Current, potential difference, Ohm's law, resistance combinations, heating effects, electric power.",
            "topics": [
                {"topic_number": 1, "title": "Electric Current, Potential Difference and Ohm's Law", "estimated_minutes": 25, "description": "Circuit diagrams, V-I characteristics, resistance and resistivity."},
                {"topic_number": 2, "title": "Series and Parallel Combinations of Resistors", "estimated_minutes": 30, "description": "Equivalent resistance derivation, practical applications in household wiring."},
                {"topic_number": 3, "title": "Joule's Law of Heating and Electric Power", "estimated_minutes": 25, "description": "Heating applications (fuse, iron, heater), electric power formula, commercial unit kWh."},
            ],
        },
        {
            "chapter_number": 12,
            "title": "Magnetic Effects of Electric Current",
            "description": "Magnetic field and field lines, electromagnetic force, Fleming's rules, domestic electrical wiring.",
            "topics": [
                {"topic_number": 1, "title": "Magnetic Field Lines and Current-Carrying Conductors", "estimated_minutes": 25, "description": "Right hand thumb rule, magnetic field of straight wire, circular loop, and solenoid."},
                {"topic_number": 2, "title": "Force on Current-Carrying Conductor and Fleming's Left Hand Rule", "estimated_minutes": 25, "description": "Magnetic force principle, direction rules, electric motor working principle."},
                {"topic_number": 3, "title": "Domestic Electric Circuits and Electrical Safety", "estimated_minutes": 20, "description": "Live, neutral, earth wires; overloading, short circuiting, earthing importance."},
            ],
        },
        {
            "chapter_number": 13,
            "title": "Our Environment",
            "description": "Ecosystem components, trophic levels, biological magnification, ozone layer depletion, solid waste management.",
            "topics": [
                {"topic_number": 1, "title": "Ecosystem, Food Chains, and Energy Flow", "estimated_minutes": 20, "description": "Producers, consumers, decomposers; 10 percent law of energy transfer."},
                {"topic_number": 2, "title": "Ozone Layer Depletion and Waste Management", "estimated_minutes": 20, "description": "CFCs role in ozone hole, biodegradable vs non-biodegradable waste, recycling."},
            ],
        },
    ],
}


# Exemplar 2: CBSE Class 10 Mathematics Standard (Code 041) - 14 Official NCERT Chapters
CBSE_10_MATH_SYLLABUS = {
    "code": "cbse-class-10-math-std",
    "name": "Mathematics Standard",
    "board": "CBSE",
    "grade": "Class 10",
    "academic_stream": None,
    "chapters": [
        {
            "chapter_number": 1,
            "title": "Real Numbers",
            "description": "Fundamental Theorem of Arithmetic, statements after reviewing work done earlier and after illustrating and motivating through examples, Proofs of irrationality of √2, √3, √5.",
            "topics": [
                {"topic_number": 1, "title": "The Fundamental Theorem of Arithmetic", "estimated_minutes": 25, "description": "Prime factorisation, HCF and LCM calculations using prime factors."},
                {"topic_number": 2, "title": "Revisiting Irrational Numbers and Proofs", "estimated_minutes": 25, "description": "Rigorous proofs of irrationality for √2, √3, √5 and algebraic combinations."},
            ],
        },
        {
            "chapter_number": 2,
            "title": "Polynomials",
            "description": "Zeros of a polynomial, Relationship between zeros and coefficients of quadratic polynomials.",
            "topics": [
                {"topic_number": 1, "title": "Geometrical Meaning of the Zeros of a Polynomial", "estimated_minutes": 20, "description": "Parabolic graphs, number of real zeros from graphical intersections."},
                {"topic_number": 2, "title": "Relationship between Zeros and Coefficients", "estimated_minutes": 25, "description": "Sum and product of zeros of quadratic polynomials, formation of quadratic expressions."},
            ],
        },
        {
            "chapter_number": 3,
            "title": "Pair of Linear Equations in Two Variables",
            "description": "Pair of linear equations in two variables and graphical method of their solution, consistency/inconsistency, algebraic conditions.",
            "topics": [
                {"topic_number": 1, "title": "Graphical Method of Solution and Consistency", "estimated_minutes": 25, "description": "Intersecting, parallel, and coincident lines; consistent vs inconsistent systems."},
                {"topic_number": 2, "title": "Algebraic Methods: Substitution and Elimination", "estimated_minutes": 30, "description": "Solving linear systems algebraically; word problems on numbers, ages, fractions, speed."},
            ],
        },
        {
            "chapter_number": 4,
            "title": "Quadratic Equations",
            "description": "Standard form of a quadratic equation ax² + bx + c = 0, solutions by factorisation and by quadratic formula, nature of roots.",
            "topics": [
                {"topic_number": 1, "title": "Solution by Factorisation and Splitting the Middle Term", "estimated_minutes": 25, "description": "Finding roots through factoring quadratic polynomials."},
                {"topic_number": 2, "title": "The Quadratic Formula and Nature of Roots", "estimated_minutes": 30, "description": "Discriminant D = b² - 4ac, real and distinct, real and equal, or non-real roots."},
            ],
        },
        {
            "chapter_number": 5,
            "title": "Arithmetic Progressions",
            "description": "Standard form of AP, nth term of an AP and sum of the first n terms of an AP and their application in solving daily life problems.",
            "topics": [
                {"topic_number": 1, "title": "General Term (nth term) of an AP", "estimated_minutes": 25, "description": "Formula an = a + (n-1)d, finding terms, identifying terms from end."},
                {"topic_number": 2, "title": "Sum of First n Terms of an AP", "estimated_minutes": 30, "description": "Formula Sn = n/2(2a + (n-1)d), word problems involving series summation."},
            ],
        },
        {
            "chapter_number": 6,
            "title": "Triangles",
            "description": "Definitions, examples, counter examples of similar triangles, Basic Proportionality Theorem, similarity criteria (AAA, SSS, SAS).",
            "topics": [
                {"topic_number": 1, "title": "Basic Proportionality Theorem (Thales' Theorem)", "estimated_minutes": 30, "description": "Statement, proof, and converse of BPT with applications."},
                {"topic_number": 2, "title": "Criteria for Similarity of Triangles (AAA, SSS, SAS)", "estimated_minutes": 30, "description": "Applying similarity criteria to solve geometric proofs and numerical lengths."},
            ],
        },
        {
            "chapter_number": 7,
            "title": "Coordinate Geometry",
            "description": "Review of coordinate geometry concepts, graphs of linear equations, distance formula, section formula (internal division).",
            "topics": [
                {"topic_number": 1, "title": "The Distance Formula", "estimated_minutes": 20, "description": "Calculating distance between two points, collinearity, quadrilateral classifications."},
                {"topic_number": 2, "title": "Section Formula and Mid-point Formula", "estimated_minutes": 25, "description": "Internal division of line segment in ratio m1:m2, coordinates of midpoint."},
            ],
        },
        {
            "chapter_number": 8,
            "title": "Introduction to Trigonometry",
            "description": "Trigonometric ratios of an acute angle of a right-angled triangle, values of trigonometric ratios of 30°, 45° and 60°, trigonometric identities.",
            "topics": [
                {"topic_number": 1, "title": "Trigonometric Ratios in a Right Triangle", "estimated_minutes": 25, "description": "Sine, cosine, tangent, cotangent, secant, cosecant of acute angles."},
                {"topic_number": 2, "title": "Ratios of Specific Angles (0°, 30°, 45°, 60°, 90°)", "estimated_minutes": 20, "description": "Evaluating numerical trigonometric expressions using standard angle table."},
                {"topic_number": 3, "title": "Fundamental Trigonometric Identity sin²θ + cos²θ = 1", "estimated_minutes": 30, "description": "Proofs and applications of Pythagorean trigonometric identities."},
            ],
        },
        {
            "chapter_number": 9,
            "title": "Some Applications of Trigonometry",
            "description": "Heights and Distances: Angle of elevation, Angle of Depression, simple problems on heights and distances.",
            "topics": [
                {"topic_number": 1, "title": "Angles of Elevation and Depression", "estimated_minutes": 30, "description": "Solving single-triangle and two-triangle height/distance word problems with 30°, 45°, 60°."},
            ],
        },
        {
            "chapter_number": 10,
            "title": "Circles",
            "description": "Tangent to a circle at point of contact, proofs that tangent is perpendicular to radius and tangents from external point are equal.",
            "topics": [
                {"topic_number": 1, "title": "Tangents to a Circle and Theorems", "estimated_minutes": 25, "description": "Tangent-radius perpendicularity theorem, tangents from external point theorem."},
                {"topic_number": 2, "title": "Geometric Proofs and Inscribed Circles", "estimated_minutes": 30, "description": "Circumscribing and inscribing polygons, numerical tangent calculations."},
            ],
        },
        {
            "chapter_number": 11,
            "title": "Areas Related to Circles",
            "description": "Area of sectors and segments of a circle, problems based on areas and perimeter / circumference of plane figures.",
            "topics": [
                {"topic_number": 1, "title": "Perimeter and Area of Circle Review", "estimated_minutes": 20, "description": "Circumference and area formulas, concentric circle problems."},
                {"topic_number": 2, "title": "Areas of Sector and Segment of a Circle", "estimated_minutes": 30, "description": "Formulas for sector area θ/360 * πr², length of arc, and minor/major segment areas."},
            ],
        },
        {
            "chapter_number": 12,
            "title": "Surface Areas and Volumes",
            "description": "Surface areas and volumes of combinations of any two: cubes, cuboids, spheres, hemispheres and right circular cylinders/cones.",
            "topics": [
                {"topic_number": 1, "title": "Surface Area of Combined Solids", "estimated_minutes": 30, "description": "Calculating total surface area of combined geometric forms."},
                {"topic_number": 2, "title": "Volume of Combined Solids", "estimated_minutes": 30, "description": "Finding volume of composite solids without internal cavities."},
            ],
        },
        {
            "chapter_number": 13,
            "title": "Statistics",
            "description": "Mean, median and mode of grouped data (bimodal situation to be avoided).",
            "topics": [
                {"topic_number": 1, "title": "Mean of Grouped Data (Direct and Assumed Mean Methods)", "estimated_minutes": 25, "description": "Computing arithmetic mean using class marks and frequency tables."},
                {"topic_number": 2, "title": "Mode of Grouped Data", "estimated_minutes": 20, "description": "Modal class identification and mode formula execution."},
                {"topic_number": 3, "title": "Median of Grouped Data", "estimated_minutes": 25, "description": "Cumulative frequency distribution, median class, and median formula."},
            ],
        },
        {
            "chapter_number": 14,
            "title": "Probability",
            "description": "Classical definition of probability, simple problems on finding the probability of an event.",
            "topics": [
                {"topic_number": 1, "title": "Classical Theoretical Probability", "estimated_minutes": 25, "description": "Elementary events, impossible events, sure events, coin, die, and card problems."},
            ],
        },
    ],
}


# Exemplar 3: CBSE Class 12 Physics (Code 042) - 14 Official NCERT Chapters
CBSE_12_PHYSICS_SYLLABUS = {
    "code": "cbse-class-12-sci-phy",
    "name": "Physics",
    "board": "CBSE",
    "grade": "Class 12",
    "academic_stream": "Science",
    "chapters": [
        {"chapter_number": 1, "title": "Electric Charges and Fields", "description": "Coulomb's law, electric field lines, electric dipole, Gauss's law and applications."},
        {"chapter_number": 2, "title": "Electrostatic Potential and Capacitance", "description": "Electric potential, equipotential surfaces, conductors, capacitors, dielectric polarization."},
        {"chapter_number": 3, "title": "Current Electricity", "description": "Drift velocity, Ohm's law, resistivity, Kirchhoff's rules, Wheatstone bridge."},
        {"chapter_number": 4, "title": "Moving Charges and Magnetism", "description": "Biot-Savart law, Ampere's circuital law, Lorentz force, cyclotron, moving coil galvanometer."},
        {"chapter_number": 5, "title": "Magnetism and Matter", "description": "Magnetic dipole, Earth's magnetism, dia-, para-, and ferromagnetic substances."},
        {"chapter_number": 6, "title": "Electromagnetic Induction", "description": "Faraday's laws, Lenz's law, eddy currents, self and mutual induction."},
        {"chapter_number": 7, "title": "Alternating Current", "description": "Peak and RMS values, LCR series circuit, resonance, power in AC circuits, AC generator, transformer."},
        {"chapter_number": 8, "title": "Electromagnetic Waves", "description": "Displacement current, electromagnetic spectrum, characteristics and propagation."},
        {"chapter_number": 9, "title": "Ray Optics and Optical Instruments", "description": "Refraction at spherical surfaces, lenses, prism dispersion, microscope and telescope."},
        {"chapter_number": 10, "title": "Wave Optics", "description": "Huygens' principle, wave fronts, Young's double slit interference, single slit diffraction."},
        {"chapter_number": 11, "title": "Dual Nature of Radiation and Matter", "description": "Photoelectric effect, Einstein's photoelectric equation, de Broglie relation."},
        {"chapter_number": 12, "title": "Atoms", "description": "Alpha-particle scattering experiment, Rutherford's model, Bohr's model, hydrogen line spectra."},
        {"chapter_number": 13, "title": "Nuclei", "description": "Nuclear composition, mass defect, binding energy per nucleon, nuclear fission and fusion."},
        {"chapter_number": 14, "title": "Semiconductor Electronics: Materials, Devices and Simple Circuits", "description": "Energy bands, intrinsic and extrinsic semiconductors, p-n junction diode, rectification."},
    ],
}


# Exemplar 4: ICSE Class 10 History, Civics and Geography (HCG) - 12 Official Chapters
ICSE_10_HCG_SYLLABUS = {
    "code": "icse-class-10-hcg",
    "name": "History, Civics and Geography",
    "board": "ICSE",
    "grade": "Class 10",
    "academic_stream": None,
    "chapters": [
        # Civics
        {"chapter_number": 1, "title": "The Union Parliament", "description": "Lok Sabha and Rajya Sabha: composition, qualifications, powers, legislative procedures."},
        {"chapter_number": 2, "title": "The President and the Vice-President", "description": "Qualifications, election procedure, executive, legislative, and emergency powers."},
        {"chapter_number": 3, "title": "Prime Minister and Council of Ministers", "description": "Appointment, position, functions, cabinet responsibility and collective accountability."},
        {"chapter_number": 4, "title": "The Supreme Court", "description": "Composition, qualifications, original, appellate, and advisory jurisdictions, judicial review."},
        {"chapter_number": 5, "title": "The High Courts and Subordinate Courts", "description": "High Court jurisdiction, Lok Adalats: meaning, composition, advantages."},
        # History
        {"chapter_number": 6, "title": "The First War of Independence, 1857", "description": "Causes: political, socio-religious, economic, military; consequences and Queen's Proclamation."},
        {"chapter_number": 7, "title": "Growth of Nationalism and Early Nationalists", "description": "Factors promoting nationalism; methods and contributions of Early Nationalists."},
        {"chapter_number": 8, "title": "Assertive Nationalists and the Partition of Bengal", "description": "Causes of Partition, Swadeshi and Boycott movements, Assertive leaders (Lal-Bal-Pal)."},
        {"chapter_number": 9, "title": "The Muslim League and Lucknow Pact", "description": "Formation of Muslim League, objectives, Lucknow Pact of 1916 significance."},
        {"chapter_number": 10, "title": "Mahatma Gandhi and National Movement", "description": "Non-Cooperation Movement, Civil Disobedience Movement, Quit India Movement."},
        {"chapter_number": 11, "title": "The Forward Bloc, INA, and Independence", "description": "Subhas Chandra Bose, Forward Bloc objectives, INA contributions, Mountbatten Plan."},
        {"chapter_number": 12, "title": "The Contemporary World: World Wars & United Nations", "description": "First World War causes, Treaty of Versailles, Rise of Fascism and Nazism, Second World War, UN objectives and principal organs."},
    ],
}
