"""create_curriculum_intelligence_tables

Revision ID: 244570d98dae
Revises: f4f3f9759b20
Create Date: 2026-09-22 21:15:49.254181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244570d98dae'
down_revision: Union[str, Sequence[str], None] = 'f4f3f9759b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_objectives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('taxonomy_level', sa.String(length=50), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'code', name='uq_topic_objective_code')
    )
    op.create_index('ix_learning_objectives_topic', 'learning_objectives', ['topic_id'], unique=False)
    op.create_index(op.f('ix_learning_objectives_topic_id'), 'learning_objectives', ['topic_id'], unique=False)
    op.create_table('previous_year_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('board', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('exam_year', sa.Integer(), nullable=False),
    sa.Column('paper_code', sa.String(length=100), nullable=False),
    sa.Column('question_number', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('marking_scheme', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_previous_year_questions_subject_id'), 'previous_year_questions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_previous_year_questions_topic_id'), 'previous_year_questions', ['topic_id'], unique=False)
    op.create_index('ix_pyqs_board_year', 'previous_year_questions', ['board', 'exam_year'], unique=False)
    op.create_index('ix_pyqs_subject_topic', 'previous_year_questions', ['subject_id', 'topic_id'], unique=False)
    op.create_table('topic_study_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('notes_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('learning_objectives_json', sa.JSON(), nullable=True),
    sa.Column('explanation_markdown', sa.Text(), nullable=False),
    sa.Column('key_terms_json', sa.JSON(), nullable=True),
    sa.Column('formulas_and_dates_json', sa.JSON(), nullable=True),
    sa.Column('diagrams_json', sa.JSON(), nullable=True),
    sa.Column('common_misconceptions_json', sa.JSON(), nullable=True),
    sa.Column('exam_points_json', sa.JSON(), nullable=True),
    sa.Column('practice_questions_json', sa.JSON(), nullable=True),
    sa.Column('source_references_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'notes_type', name='uq_topic_notes_type')
    )
    op.create_index('ix_topic_notes_type', 'topic_study_notes', ['topic_id', 'notes_type'], unique=False)
    op.create_index(op.f('ix_topic_study_notes_topic_id'), 'topic_study_notes', ['topic_id'], unique=False)
    op.create_table('practice_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('learning_objective_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('generation_provenance', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learning_objective_id'], ['learning_objectives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_practice_questions_difficulty', 'practice_questions', ['difficulty'], unique=False)
    op.create_index('ix_practice_questions_topic', 'practice_questions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_practice_questions_topic_id'), 'practice_questions', ['topic_id'], unique=False)
    op.create_table('student_question_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('pyq_id', sa.Integer(), nullable=True),
    sa.Column('practice_question_id', sa.Integer(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_question_id'], ['practice_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pyq_id'], ['previous_year_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempts_practice', 'student_question_attempts', ['practice_question_id'], unique=False)
    op.create_index('ix_attempts_pyq', 'student_question_attempts', ['pyq_id'], unique=False)
    op.create_index('ix_attempts_user_topic', 'student_question_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_question_attempts_user_id'), 'student_question_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_question_attempts_user_id'), table_name='student_question_attempts')
    op.drop_index('ix_attempts_user_topic', table_name='student_question_attempts')
    op.drop_index('ix_attempts_pyq', table_name='student_question_attempts')
    op.drop_index('ix_attempts_practice', table_name='student_question_attempts')
    op.drop_table('student_question_attempts')
    op.drop_index(op.f('ix_practice_questions_topic_id'), table_name='practice_questions')
    op.drop_index('ix_practice_questions_topic', table_name='practice_questions')
    op.drop_index('ix_practice_questions_difficulty', table_name='practice_questions')
    op.drop_table('practice_questions')
    op.drop_index(op.f('ix_topic_study_notes_topic_id'), table_name='topic_study_notes')
    op.drop_index('ix_topic_notes_type', table_name='topic_study_notes')
    op.drop_table('topic_study_notes')
    op.drop_index('ix_pyqs_subject_topic', table_name='previous_year_questions')
    op.drop_index('ix_pyqs_board_year', table_name='previous_year_questions')
    op.drop_index(op.f('ix_previous_year_questions_topic_id'), table_name='previous_year_questions')
    op.drop_index(op.f('ix_previous_year_questions_subject_id'), table_name='previous_year_questions')
    op.drop_table('previous_year_questions')
    op.drop_index(op.f('ix_learning_objectives_topic_id'), table_name='learning_objectives')
    op.drop_index('ix_learning_objectives_topic', table_name='learning_objectives')
    op.drop_table('learning_objectives')
    # ### end Alembic commands ###
